% BEHAVIOR
%
% Files
%   align_tracking               - Align behavior tracking trajectory with detected pulses
%   AngularVelocity              - Compute instantaneous angular velocity.
%   behavioral_ROI_locator       - Locate behavioral regions of interest (ROIs) in a video for a given session.
%   behaviorStructureDescription - Instruction file guiding you through the expected structure of behavoir files
%   check_for_dlc                - Folder checker for dlc files
%   DefineZone                   - Define a restricted zone to which analyses can be circumscribed.
%   detectLED                    - Detect red and blue LEDs position in a video file and creates a 'led' file
%   find_and_move_videos         - Matlab wrapper for find_and_move_videos.py
%   FindLapsNSMAadapted          - Find laps in a track of horseshoe-geometry
%   general_behavior_file        - Converts multiple tracking data types to the format of CellExplorer.
%   getSessionTracking           - Get position tracking for subsession, concatenate, and align to ephys recording
%   IsInZone                     - Test whether the animal is in a given zone.
%   KalmanVel                    - Velocity estimation using the Kalman Filter on recorded position.
%   LED2Tracking                 - Get LED tracking from .avi and digitalin.dat files
%   linearTrackBehavior          - Generate behavioral file for linear track sessions.
%   LinearVelocity               - Compute instantaneous linear velocity.
%   load_dlc_csv                 - General function to load dlc csv files.
%   make_pre_task_post           - Generate pre/task/post structure.
%   manual_trackerjumps          - Manually cut out xy coordinates that are outside the bounds of your maze.
%   maze_distance_gui            - maze_distance_gui: manually get distance between points in pixels
%   MovementPeriods              - Find periods of movement (opposite of QuietPeriods)
%   NSMAFindGoodLaps             - Find good laps generated by FindLaps.
%   objPlaceScore                - Score memory performance in object location task.
%   Plot_recording_States        - Plot recording states - unclear if used, Raly will remove
%   preferenceScore              - Score object task behavior.
%   process_and_sync_dlc         - Unpack DLC CSV within subfolders.
%   QuietPeriods                 - Find periods of immobility.
%   readOptitrackCSV             - Read optitrack CVS into matlab.
%   RotateCoordinates            - Rotates x and y coordinates around a center point by an angle.
%   Threshold                    - Find periods where samples lay above or below a given threshold
%   trajectory_kalman_filter     - Perform Kalman filter on raw video tracker data to estimate animal trajectory.
