name: MATLAB CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout external repository
        uses: actions/checkout@v2
        with:
          repository: ayalab1/CellExplorer
          path: CellExplorer

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Compile MEX files
        run: |
          matlab -batch "cd utilities/intervalsC+; mex CountInIntervals.c; mex FindInInterval.c; mex MatchUpIndices.c"
          matlab -batch "cd utilities/mapsC+; mex Contiguous.c; mex FindField.c"

      - name: Run MATLAB tests
        run: |
          matlab -batch "addpath(genpath('.')); addpath('CellExplorer/calc_CellMetrics/LoadBinary.m'); results = runtests('test'); assertSuccess(results);"