name: MATLAB CI

on:
  push:
    branches:
      - add-CI
  pull_request:
    branches:
      - add-CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: List directory contents (debug step)
        run: ls -R

      - name: Run MATLAB tests
        run: |
          matlab -batch "addpath(genpath('.')); results = runtests('test', 'IncludeSubfolders', true); assertSuccess(results);"
